version: '3.9'
name: mlflow
services:
  mlflow:
    build: ./containers/mlflow
    container_name: mlflow
    ports:
      - 5000:5000
    environment:
      - MUID=$UID
      - MGID=$GID
      - USER=$(whoami)
      # - POSTGRES_DB=mlruns
      # - POSTGRES_USER=mlflow
      # - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    command: mlflow server -h 0.0.0.0 -p 5000 \
              --default-artifact-root file:///home/$USER/mlflowProjects/artifacts
              # --backend-store-uri $BACKEND \
    # volumes:
    #   - ./mlflowProjects:/home/$USER/mlflowProjects

    networks:
      - backend
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    environment:
      - MLFLOW_DOMAIN=$MLFLOW_DOMAIN
      - STATUS_DOMAIN=$STATUS_DOMAIN
    volumes:
      - ./containers/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./containers/nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      # - mlflow-users:/etc/nginx
    depends_on:
      - mlflow
    networks:
      - backend
      - frontend

  uptime-kuma:
    restart: always
    ports:
        - 3001:3001
    volumes:
        - uptime-kuma:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    networks:
      - backend
      - frontend


networks:
  backend:
  frontend:

volumes:
#   mlflow-users:  
  uptime-kuma: