version: '3.9'
services:
  mlflow:
    build: ./containers/mlflow
    
    container_name: mlflow
    
    ports:
      - 5000:5000
    
    environment:
      - MUID=$UID
      - MGID=$GID
      - USER=$(whoami)
      # - POSTGRES_DB=mlruns
      # - POSTGRES_USER=mlflow
      # - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    
    command: mlflow server -h 0.0.0.0 -p 5000 \
              --default-artifact-root file:///home/$USER/mlflowProjects/artifacts
              # --backend-store-uri $BACKEND \
    
    # volumes:
    #   - ./mlflowProjects:/home/$USER/mlflowProjects

    # networks:
    #   - backend
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80

    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - mlflow-users:/etc/nginx

    depends_on:
      - mlflow

    # networks:
    #   - backend
    #   - frontend

# networks:
#   backend:
#   frontend:

# volumes:
#   mlflow-users:  
