version: '3.9'
name: mlflow
services:
  mlflow:
    build: ./containers/mlflow
    container_name: mlflow
    env_file: 
      - .env
    ports:
      - 5000:5000
    environment:
      - MUID=$UID
      - MGID=$GID
      - USER=$(whoami)
      - AWS_REGION=us-east-2
    command: >
      mlflow server -h 0.0.0.0 -p 5000
      --backend-store-uri postgresql://mlflow:${POSTGRES_PASSWORD}@postgresql:5432/mlruns
      --default-artifact-root s3://mlflow-artifacts-alonmadrid/artifacts

    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgresql:
    image: postgres:16.3
    container_name: postgres
    environment:
      - MUID=$UID
      - MGID=$GID
      - POSTGRES_DB=mlruns
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/database

    # restart: unless-stopped

    ports:
      - 5432:5432

    volumes:
      - mlrunsvol:/var/lib/postgresql:rw

    networks:
      - backend
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    environment:
      - MLFLOW_DOMAIN=$MLFLOW_DOMAIN
      - STATUS_DOMAIN=$STATUS_DOMAIN
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./containers/nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:rw
      # - mlflow-users:/etc/nginx
    depends_on:
      - mlflow
    networks:
      - backend
      - frontend

  uptime-kuma:
    restart: always
    ports:
        - 3001:3001
    volumes:
        - uptime-kuma:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    networks:
      - backend
      - frontend


networks:
  backend:
  frontend:

volumes:
#   mlflow-users:  
  uptime-kuma:
  mlrunsvol:
